name: PHP Composer

on:
  push:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  run:
    runs-on: self-hosted
    strategy:
      matrix:
        php-versions: ['7.4']
    name: PHP ${{ matrix.php-versions }}
    steps:
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
      env:
        runner: self-hosted

    - name: Update server files
      run: |
        /usr/bin/ssh ubuntu@react.avinthasandaruwan.me << EOF
        cd /home/ubuntu/web_project/_work/web_project/web_project
        git pull origin master
        composer install
        php artisan migrate
        exit
      EOF
