name: PHP Composer

on:
  push:
    branches: [ "master" ]


permissions:
  contents: read

jobs:
  run:
    runs-on: self-hosted
    strategy:
      matrix:
        php-versions: ['7.4']
    name: PHP ${{ matrix.php-versions }}
    steps:
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
      env:
        runner: self-hosted
