name: Deploy

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Rsync
      uses: actions/rsync@v2
      with:
        source: .
        destination: /home/ubuntu/web_project/_work/web_project/web_project
        
    - name: Restart Nginx
      run: sudo service nginx restart
